#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the angryProfessor function below.
def angryProfessor(k, a):
    #l=[]
    #l=list(a)
    #l1=len(l)
    k1=0
    for i in range(n):
        if a[i]<=0:
            k1=k1+1
        else:
            k1=k1
   
    
    if k1>=k:
        return("NO")
    else:
        return("YES")
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        nk = input().split()

        n = int(nk[0])

        k = int(nk[1])

        a = list(map(int, input().rstrip().split()))

        result = angryProfessor(k, a)
        #angryProfessor(k, a)
        fptr.write(result + '\n')

    fptr.close()
