#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the catAndMouse function below.
def catAndMouse(x, y, z):
    a1=a=0
    b1=b=0
    a=z-x
    a1=abs(a)
    b=z-y
    b1=abs(b)
    if a1<b1:
        return("Cat A")
    elif b1==a1:
        return("Mouse C")
    else:
        return("Cat B")
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        xyz = input().split()

        x = int(xyz[0])

        y = int(xyz[1])

        z = int(xyz[2])

        result = catAndMouse(x, y, z)

        fptr.write(result + '\n')

    fptr.close()
