#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the utopianTree function below.
def utopianTree(n):
    for i in range(n+1):
        if i==0:
            m=1
        else:
            #while i!=n:
            if (i%2==0):
                m=m+1
            else:
                m=m*2
    return m
                    
            


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        n = int(input())

        result = utopianTree(n)

        fptr.write(str(result) + '\n')

    fptr.close()
