#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the viralAdvertising function below.
def viralAdvertising(n):
    x=5
    x1=0
    x2=0
    for i in range(n):
        x1=x/2
        x1=int(x1)
        x2=x2+x1
        x=x1*3
    return(x2)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    result = viralAdvertising(n)

    fptr.write(str(result) + '\n')

    fptr.close()
